media: media
content:
  - name: pages
    label: Pages
    type: collection
    path: words/posts
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
      - name: tags
        type: select
        options:
          multiple: true
      - name: date
        type: date
        options:
        format: yyyy-MM-dd
        